model_ckpt_path: "./trained_params/epoch_99.valminade_0.029.250822.ParkE2E.pth"
training_config: "training_real"
predict_mode: "topic"

trajectory_pub_frequency: 1
cam_info_dir: "./utils"
progress_threshold: 0.97