model_ckpt_path: "./trained_params/epoch_9.valminade_1.343.250820.ParkE2E.pth"
training_config: "training_real"
predict_mode: "topic"

trajectory_pub_frequency: 1
cam_info_dir: "./utils"
progress_threshold: 0.97