##################### Dataset Options #####################
data_dir: './e2e_dataset/'
training_dir: "train"
validation_dir: "val"
test_dir: "test"

##################### Basic Options #####################
data_mode: "real_scene"
num_gpus: 1
cuda_device_index: "0"
log_root_dir: './log/'
checkpoint_root_dir: './ckpt'
log_every_n_steps: 10
check_val_every_n_epoch: 5
epochs: 40
learning_rate: 0.0001
weight_decay: 0.00001
batch_size: 32
num_workers: 8
# resume_path: ""

##################### Data Process #####################
autoregressive_points: 30
traj_downsample_stride: 3
item_number: 2
token_nums: 300
append_token: 3
xy_max: 3
process_dim: [256, 256]

##################### BEV Encoder #####################
bev_encoder_in_channel: 64
bev_x_bound: [-10.0, 10.0, 0.1]
bev_y_bound: [-10.0, 10.0, 0.1]
bev_z_bound: [-10.0, 10.0, 20.0]
d_bound: [0.5, 12.5, 0.25]
final_dim: [256, 256]
bev_down_sample: 8
backbone: "efficientnet-b4"

##################### Target #####################
add_noise_to_target: true
target_noise_threshold: 0.5
target_range: 1.4
use_fuzzy_target: false

##################### BEV Query #####################
fusion_method: "query"
query_en_dim: 256
query_en_heads: 4
query_en_layers: 4
query_en_dropout: 0.05
query_en_bev_length: 256

##################### Decoder #####################
decoder_method: "transformer"
tf_de_dim: 128
tf_de_heads: 4
tf_de_layers: 4
tf_de_dropout: 0.1


in_channels: 11
num_subgraph_layers: 3
subgraph_width: 64
global_graph_width: 128
max_id: 50
traj_norm_x_min: -2.898744583129883
traj_norm_x_max: 2.899961471557617
traj_norm_y_min: -0.9972971677780151
traj_norm_y_max: 0.5519722104072571
graph_norm_x_min: -15.825324058532715
graph_norm_x_max: 16.95151710510254
graph_norm_y_min: -14.40243911743164
graph_norm_y_max: 15.261693954467773
graph_norm_theta_min: -3.1399965286254883
graph_norm_theta_max: 3.1399965286254883
target_point_x_min: -7.874159336090088
target_point_x_max: 3.3416473865509033
target_point_y_min: -7.363075256347656
target_point_y_max: 0.05854923278093338
target_point_theta_min: -0.07990014553070068
target_point_theta_max: 1.6548668146133423
